### ISSUE TITLE
Class 'Carbon\Carbon' not found 

### ISSUE THREAD

**Issue by pgsutariya** [sndsabin/Aragorn-Job-Manager-Magento2#1]
Fatal error: Uncaught Error: Class 'Carbon\Carbon' not found in /var/www/html/magento223/app/code/Aragorn/JobManager/Model/Job.php:168

**Comment by sndsabin** [comment]
You have missed the second step of installation. Please install Carbon Package in Magento **root directory** via composer. **cd** into your **root directory**, then

`composer require nesbot/carbon`

**Comment by sndsabin** [comment]
@pgsutariya Did it work ? if so, we should close this issue.

**Comment by pgsutariya** [comment]
@sndsabin Thanks for your help. It's working like charm...
You may close this issue...
Thank you again...

**Comment by sndsabin** [comment]
welcome 😄
