### ISSUE TITLE
CSS problem

### ISSUE THREAD

**Issue by komalmm** [sndsabin/Aragorn-Job-Manager-Magento2#3]
Hi css is working fine for no job posting. If I post a new job then my css not working please help

**Comment by sndsabin** [comment]
CSS not working ? try deploying static content and see that might help.

`php bin/magento setup:static-content:deploy -f `

**Comment by komalmm** [comment]
I tried this command but same thing showing
![github1](https://user-images.githubusercontent.com/42463729/44298602-a39ced00-a303-11e8-8e7f-8fe0b4da20bd.PNG)

**Comment by komalmm** [comment]
It is not showing with header and footer...If I delete job post abc.. then css is working fine with header and footer...I am not getting why after adding job, I am getting this..Please help

**Comment by sndsabin** [comment]
Did you install carbon library ? You might have missed step 2 of the installation process. 
**Aragorn JobManager** uses _Carbon_ library. **cd** into your **magento root directory** and install the carbon package via composer

`composer require nesbot/carbon`

**Comment by komalmm** [comment]
Hi,

I have added this command.. On this it was going to next line.. It was not
showing any progress

**Comment by sndsabin** [comment]
On this it was going to next line..It was not showing any progress ?Please elaborate. Any screenshot or details would help.

**Comment by komalmm** [comment]
ok just a minute

**Comment by komalmm** [comment]
![github2](https://user-images.githubusercontent.com/42463729/44302960-a7576080-a351-11e8-9557-365de2de3b86.PNG)

**Comment by sndsabin** [comment]
Do you have composer installed on your machine ?

**Comment by komalmm** [comment]
after adding this command it is going to next line..this is root directory of my project

**Comment by komalmm** [comment]
I dont know about it...I am new.. can you tell me how to check it

**Comment by sndsabin** [comment]
try `composer` on command line. if it says unknown command or else it's not installed.

**Comment by sndsabin** [comment]
Try installing [composer](https://getcomposer.org/download/) if not installed. then 

`composer require nesbot/carbon`
`php bin/magento setup:upgrade`

**Comment by komalmm** [comment]
After adding composer, it goes on next line like previous one.. no error or no statement

**Comment by sndsabin** [comment]
Composer isn't installed  or it's alias is not created. If composer is installed, it must spit out something like this. 

![composer](https://user-images.githubusercontent.com/9588306/44303026-ba6c2f80-a355-11e8-9083-bc0e16ead6f6.png)

**Comment by komalmm** [comment]
Ok thank you sir...I just want to know that if I install composer now in my project...so my data on website will remain same na...I mean it should not affect somewhere on my site

**Comment by sndsabin** [comment]
shouldn't affect

**Comment by komalmm** [comment]
Ok thank you sir

**Comment by komalmm** [comment]
Can I manually add nesbot/carbon file in this module

**Comment by sndsabin** [comment]
Yes, you could but not recommended

**Comment by komalmm** [comment]
> Yes, you could but not recommended

Import failed: Warning: Error while sending QUERY packet. PID=69 in /home/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php on line 228

Getting this error after setup:upgrade

**Comment by komalmm** [comment]
> > Yes, you could but not recommended
> 
> Import failed: Warning: Error while sending QUERY packet. PID=69 in /home/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php on line 228
> 
> Getting this error after setup:upgrade

Hi...
I am creating jobs in Magento Admin, but on the frontend I am getting only last one job with no heade and footer.
Please refer:  http://prntscr.com/lb2yjf

**Comment by sndsabin** [comment]
Did you install carbon library ? If not please refer to [this](https://github.com/sndsabin/Aragorn-Job-Manager-Magento2/issues/3#issuecomment-414083281)
