### ISSUE TITLE
Nav toggle is not working in Magento 2.1

### ISSUE THREAD

**Issue by parveen12345** [sndsabin/Aragorn-Job-Manager-Magento2#4]
I have some issue when we click on nav toggle it is not clickable please help me it's a very urgent for me if any body have any suggestions please let me know

**Comment by sndsabin** [comment]
Nav toggle ?

**Comment by parveen12345** [comment]
Yes nav toggle when we click the menu button to show categories in Mobile then menu button is not clickable

**Comment by parveen12345** [comment]
URL of my website is 173.255.247.199/magento/

**Comment by sndsabin** [comment]
Is it by anymeans related to this module ?
